name: MacBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install pre-requisites
        shell: bash
        run: |
          brew install gfortran
          brew install openblas
          brew install metis

      - name: Configure CMake
        run: |
          export LDFLAGS="-L/usr/local/opt/openblas/lib"
          export CPPFLAGS="-I/usr/local/opt/openblas/include"
          cmake -B ${{github.workspace}}/build \
                -DNASOQ_BLAS_BACKEND=OpenBLAS \
                -DNASOQ_USE_CLAPACK=ON \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target LBL_Test NASOQ_Test NASOQ_Step_Test LBLSOMOD_Test

      - name: Run Tests
        run: |
          ${{github.workspace}}/build/examples/LBL_Test 
          ${{github.workspace}}/build/examples/NASOQ_Test 
          ${{github.workspace}}/build/examples/NASOQ_Step_Test 
          ${{github.workspace}}/build/examples/LBLSOMOD_Test 
